### ISSUE TITLE
Allow filtering of war mode mismatch groups in 'Custom'?

### ISSUE THREAD

**Issue by Protuhj** [romdeau23/wow-lfgspamfilter#11]
I use the custom group finder a lot, and want to be able to ignore WM On groups, can you add the ability to filter out war mode mismatches?

**Comment by ShiraNai7** [comment]
That's not really spam-filtering related I think. But theres the [Premade Groups Filter](https://www.curseforge.com/wow/addons/premade-groups-filter) addon which can work together with LFGSpamFilter. You can put `not warmode` into the advanced query to filter out warmode groups.

**Comment by romdeau23** [comment]
That's not really spam-filtering related I think. But theres the [Premade Groups Filter](https://www.curseforge.com/wow/addons/premade-groups-filter) addon which can work together with LFGSpamFilter. You can put not warmode into the advanced query to filter out warmode groups.

**Comment by Protuhj** [comment]
It's not, but you can only really filter on so many things now (since you can't filter on the group name anymore), and this addon already filters on almost all of them, except war mode.

**Comment by romdeau23** [comment]
True, group name is not readable by addons, but [many other parameters](https://github.com/0xbs/premade-groups-filter/wiki/Keywords#properties) are. Since there's already an addon dedicated to generic filtering and it works together with LFGSpamFilter, I'd like to keep LFGSpamFilter focused solely on spam filtering and reporting.

**Comment by Protuhj** [comment]
Ok.. I'm going to fork this project then for my own needs. Thanks for your work!
